- public/chrome/logout_button.html
Remove trailing quotation marks from Logout button title
> Logout button: Remove trailing quotation marks

- lib/backend/searchguard_plugin.js
fix bug when es and kibana deployed on diff host
> fix bug when es and kibana deployed on diff host

- lib/backend/searchguard_plugin.js
Unify coding style like:
https://github.com/elastic/elasticsearch-js/blob/master/src/lib/apis/master.js#L76
> Add slash in front of fmt value

- public/apps/configuration/sections/actiongroups/controller.js
- public/apps/configuration/sections/actiongroups/views/index.html
- public/apps/configuration/sections/internalusers/controller.js
- public/apps/configuration/sections/internalusers/views/index.html
- public/apps/configuration/sections/roles/controller.js
- public/apps/configuration/sections/roles/views/index.html
- public/apps/configuration/sections/rolesmapping/controller.js
- public/apps/configuration/sections/rolesmapping/views/index.html
Adds ability to sort some of the table columns in the index views.
> ITT-1022 Make tables sortable

- public/apps/configuration/base_controller.js
- public/apps/configuration/directives/confirmationmodal/confirmationmodal.html
- public/apps/configuration/directives/confirmationmodal/confirmationmodal.js
- public/apps/configuration/directives/directives.js
- public/apps/configuration/directives/permissions/permissions.html
- public/apps/configuration/directives/permissions/permissions.js
- public/apps/configuration/sections/actiongroups/views/edit.html
- public/apps/configuration/sections/actiongroups/views/index.html
- public/apps/configuration/sections/internalusers/views/edit.html
- public/apps/configuration/sections/internalusers/views/index.html
- public/apps/configuration/sections/roles/controller.js
- public/apps/configuration/sections/roles/views/edit.html
- public/apps/configuration/sections/roles/views/index.html
- public/apps/configuration/sections/rolesmapping/views/edit.html
- public/apps/configuration/sections/rolesmapping/views/index.html
Unified confirmation dialogues with a new modal component.
> ITT-788 Unified confirmation modals

- public/apps/login/login.html
> Fix highlighting bug on login

- package.json
- public/apps/configuration/base_controller.js
- public/apps/configuration/configuration.less
- public/apps/configuration/directives/directives.js
- public/apps/configuration/directives/permissions/permissions.html
- public/apps/configuration/directives/permissions/permissions.js
- public/apps/configuration/sections/roles/controller.js
- public/apps/configuration/sections/roles/views/edit.html
- public/apps/configuration/sections/rolesmapping/controller.js
- public/apps/configuration/sections/rolesmapping/views/edit.html
Replaced the old autocomplete in favour of ui-select.
Ui-select doesn't allow for arbitrary values out of the box, so I needed to add a couple of workarounds.
> ITT 888 - Implement new autocomplete

- index.js
Disallow client certificates if not explicitly allowed in the config file.
> ITT-1118 - Disallow client certs

- public/apps/configuration/sections/system/controller.js
- public/apps/configuration/sections/system/views/edit.html
Added the ability to upload a license file in addition to pasting the license code into the textarea.
> ITT-1024 - Upload license file

- public/chrome/configuration/enable_configuration.js
This PR makes sure that the interceptor introduced in https://github.com/floragunncom/search-guard-kibana-plugin/pull/76 doesn't try to redirect to the login page when the user is already on that page.
> ITT-1218 - Do not intercept Ajax errors on login/logout

- index.js
- public/apps/multitenancy/multitenancy.html
- public/apps/multitenancy/multitenancy.js
- public/chrome/readonly/enable_readonly.js
- public/chrome/readonly/readonly.less
This PR adds read only modes, either through one or more defined roles, or through read only on the current tenant.
> Read Only Mode

- public/apps/login/login_controller.js
Login Form: Fixes a scoping issue that would prevent the error message from being shown when the user doesn't have any available tenants.
> ITT-1282 - Fix missing tenants message in the login form

- public/apps/login/login.html
Try to disable login autocomplete in browsers that support it.
> ITT-1277 - Disable login autocomplete for browsers that support it

- public/chrome/multitenancy/observe_share_links.js
Fixes an issue where converting a snapshot URL wouldn't work anymore.
Also fixes an issue where the iframe embed code was broken.
> ITT-1503 - Fixed short links in the share panel

- lib/auth/types/saml/routes.js
- public/apps/customerror/errormessage_types.js
Changed the endpoint and added a route for post logout
> ITT-1506 - Changed acs endpoint

- index.js
- lib/auth/types/kerberos/Kerberos.js
- lib/auth/types/kerberos/routes.js
Changes to the auth type as discussed
> ITT-1515 - Changed auth type

- index.js
Detects whether X-Pack is installed and makes sure the plugin does not start unless xpack.security.enabled = false.
> ITT-1507 - Check that X-Pack security is disabled if it is installed

- lib/auth/types/AuthType.js
This PR fixes a regression where the session would not be extended as configured.
> ITT-1536 - Fix session timeout

- public/chrome/configuration/enable_configuration.js
- public/chrome/readonly/enable_readonly.js
This PR fixes an issue where you would get redirected after logging out, e.g. when using JWT.
> ITT-1558 - Fixes erroneous redirect after logout

- lib/auth/types/AuthType.js
This is an attempt to fix the Kibana part of the error reported in https://github.com/floragunncom/search-guard/issues/553.
The check is identical to the check we have in later versions.
> ITT-1556 - Better check for session timeout

- package.json
Updates to a more recent version of Joi
> ITT-1583 - Update Joi dependency

- index.js
- lib/auth/frontend_bridge.js
- public/chrome/logout_button.html
- public/chrome/logout_button.js
This PR adds the logged in user's name on the instead of the "Logout" label on the logout button.
In the background, it also adds a way to pass data from the node backend to the frontend.
> ITT-576 - Display username in logout button

- lib/auth/parseNextUrl.js
- public/apps/login/get_next_url.js
This PR improves the URL parsing for the login redirects
> ITT-1658 - Better url parsing

- index.js
- lib/auth/types/basicauth/routes.js
- lib/backend/searchguard.js
- lib/session/sessionPlugin.js
- public/apps/login/login.html
- public/apps/login/login_controller.js
This PR adds an alternative login method for basic auth
> ITT-1686 - Secondary login button for third party IdPs

- lib/auth/types/AuthType.js
This PR removes some code that was accidentally added.
> ITT-1685 - Fixed Git conflict

- index.js
- lib/auth/types/proxycache/ProxyCache.js
- lib/auth/types/proxycache/parse_login_endpoint.js
- lib/auth/types/proxycache/routes.js
- public/apps/customerror/errormessage_types.js
- public/services/access_control.js
This PR introduces the new proxycache auth type.
> ITT-1769 - Proxycache auth type

- lib/auth/types/saml/routes.js
- lib/backend/searchguard.js
This PR adds the acsEndpoint to the authtoken call used by SAML
> ITT-1687 - SAML IdP initiated SSO

- index.js
- lib/auth/types/AuthType.js
- lib/multitenancy/headers.js
- public/apps/multitenancy/multitenancy.js
This PR adds support for Spaces and SG multitenancy
> ITT-1776 - Spaces and multitenancy

- index.js
- lib/multitenancy/headers.js
This PR enables support for read only tenants together with Spaces.
> ITT-1871 - Spaces + ReadOnly Tenants

- index.js
- public/apps/accountinfo/accountinfo.html
- public/apps/accountinfo/accountinfo.js
- public/apps/configuration/sections/system/controller.js
- public/apps/configuration/sections/system/views/index.html
This PR adds the Kibana plugin version information to the systems page, account overview page and the startup log file.
> #164 show plugin version information

- index.js
- public/chrome/multitenancy/enable_multitenancy.js
- public/chrome/multitenancy/observe_share_links.js
- public/chrome/readonly/enable_readonly.js
This PR adds the tenant as a query parameter for links copied from the share panels
> ITT-1564 - Add tenant to the new share panel

- index.js
This PR adds the ability to set a JWT and a tenant per query parameters.
Fixes #174
> ITT-1899 - Allow the combination of jwt and tenant query parameters

- public/apps/configuration/backend_api/actiongroups.js
- public/apps/configuration/backend_api/internalusers.js
- public/apps/configuration/backend_api/roles.js
- public/apps/configuration/backend_api/rolesmapping.js
- public/apps/configuration/sections/internalusers/controller.js
- public/apps/configuration/sections/rolesmapping/controller.js
This PR handles the case where the "readonly" property is set to false in the sg config.
Targeting 6.x here since we have other changes for 7(?).
> SGCS-210 - Better handling of the "readonly" flag

- index.js
- package.json
- public/apps/configuration-react/components/Breadcrumbs/Breadcrumbs.js
- public/apps/configuration-react/components/Breadcrumbs/index.js
- public/apps/configuration-react/components/ContentPanel/ContentPanel.js
- public/apps/configuration-react/components/ContentPanel/index.js
- public/apps/configuration-react/components/index.js
- public/apps/configuration-react/configuration/pages/CreateInternalUser/containers/CreateInternalUser/CreateInternalUser.js
- public/apps/configuration-react/index.js
- public/apps/configuration-react/less/main.less
- public/apps/configuration-react/pages/CreateInternalUser/containers/CreateInternalUser/CreateInternalUser.js
- public/apps/configuration-react/pages/CreateInternalUser/containers/CreateInternalUser/index.js
- public/apps/configuration-react/pages/CreateInternalUser/index.js
- public/apps/configuration-react/pages/Home/Home.js
- public/apps/configuration-react/pages/Home/index.js
- public/apps/configuration-react/pages/InternalUsers/containers/InternalUsers/InternalUsers.js
- public/apps/configuration-react/pages/InternalUsers/containers/InternalUsers/index.js
- public/apps/configuration-react/pages/InternalUsers/index.js
- public/apps/configuration-react/pages/Main/Main.js
- public/apps/configuration-react/pages/Main/index.js
- public/apps/configuration-react/utils/constants.js
- public/apps/configuration-react/utils/i18n_nodes.js
- public/translations/zh-CN.json
- yarn.lock
This closes
https://floragunn.atlassian.net/browse/ITT-2064?atlOrigin=eyJpIjoiNjNlZjc4Y2UwMmY3NDUzZGI5ZTRlMjQ3ZWM4ZjAxMDkiLCJwIjoiaiJ9
https://floragunn.atlassian.net/browse/ITT-2069?atlOrigin=eyJpIjoiM2VmNjdjMmJhY2Q3NDQwZWE4NmU2YzI1MDEzZTRhOTYiLCJwIjoiaiJ9
Demo (unlisted) https://youtu.be/8h-PvsVirNc
I created this PR having yarn migrate branch as a base because that PR not merged yet. I'll change the base after merging it.
> Routing for internal users section and basic UI

- package.json
- public/apps/configuration-react/pages/CreateInternalUser/containers/CreateInternalUser/CreateInternalUser.js
- public/apps/configuration-react/pages/InternalUsers/containers/InternalUsers/InternalUsers.js
- public/apps/configuration-react/pages/InternalUsers/containers/InternalUsers/utils/index.js
- public/apps/configuration-react/pages/InternalUsers/containers/InternalUsers/utils/table_user_to_user.js
- public/apps/configuration-react/pages/InternalUsers/containers/InternalUsers/utils/users_to_table_users.js
- public/apps/configuration-react/pages/Main/Main.js
- public/apps/configuration-react/utils/constants.js
- public/apps/configuration-react/utils/i18n_nodes.js
- yarn.lock
This closes
https://floragunn.atlassian.net/browse/ITT-2060
https://floragunn.atlassian.net/browse/ITT-2061
https://floragunn.atlassian.net/browse/ITT-2062
https://floragunn.atlassian.net/browse/ITT-2065
https://floragunn.atlassian.net/browse/ITT-2067
https://floragunn.atlassian.net/browse/ITT-2068
https://floragunn.atlassian.net/browse/ITT-2089
> Add internal users table

- public/apps/configuration-react/pages/InternalUsers/containers/InternalUsers/InternalUsers.js
This closes https://floragunn.atlassian.net/browse/ITT-2113
> Fix table action button name type

- public/apps/configuration-react/pages/InternalUsers/containers/InternalUsers/utils/table_user_to_user.js
This closes https://floragunn.atlassian.net/browse/ITT-2125
> Fix user cloning

- public/apps/configuration-react/pages/InternalUsers/containers/InternalUsers/InternalUsers.js
This closes https://floragunn.atlassian.net/browse/ITT-2123
> Disable checkbox for a reserved user.

- public/apps/configuration-react/pages/InternalUsers/containers/InternalUsers/InternalUsers.js
- public/apps/configuration-react/utils/constants.js
This closes https://floragunn.atlassian.net/browse/ITT-2122
> Fix internal users session storage data parse

- public/apps/configuration-react/components/Breadcrumbs/Breadcrumbs.js
- public/apps/configuration-react/index.js
- public/apps/configuration-react/less/main.less
- public/apps/configuration-react/pages/Auth/Auth.js
- public/apps/configuration-react/pages/Auth/index.js
- public/apps/configuration-react/pages/Auth/utils/constants.js
- public/apps/configuration-react/pages/Auth/utils/index.js
- public/apps/configuration-react/pages/Auth/utils/resources_to_ui_resources.js
- public/apps/configuration-react/pages/Home/Home.js
- public/apps/configuration-react/pages/Main/Main.js
- public/apps/configuration-react/utils/constants.js
- public/apps/configuration-react/utils/i18n/auth.js
- public/apps/configuration-react/utils/i18n/common.js
- public/apps/configuration-react/utils/i18n_nodes.js
This closes https://floragunn.atlassian.net/browse/ITT-2007
> Add Authentication and Authorization page

- public/apps/configuration-react/components/Breadcrumbs/Breadcrumbs.js
- public/apps/configuration-react/components/Callout/Callout.js
- public/apps/configuration-react/components/Callout/callouts/errorCallout.js
- public/apps/configuration-react/components/Callout/callouts/index.js
- public/apps/configuration-react/components/Callout/callouts/successCallout.js
- public/apps/configuration-react/components/Flyout/flyouts/customFlyout.js
- public/apps/configuration-react/components/Flyout/flyouts/index.js
- public/apps/configuration-react/components/Flyout/flyouts/inspectJson.js
- public/apps/configuration-react/components/FormControls/FormikCodeEditor/FormikCodeEditor.js
- public/apps/configuration-react/components/FormControls/FormikCodeEditor/index.js
- public/apps/configuration-react/components/index.js
- public/apps/configuration-react/pages/CreateInternalUser/containers/CreateInternalUser/CreateInternalUser.js
- public/apps/configuration-react/pages/Home/Home.js
- public/apps/configuration-react/pages/Main/Main.js
- public/apps/configuration-react/pages/SystemStatus/SystemStatus.js
- public/apps/configuration-react/pages/SystemStatus/components/UploadLicense/UploadLicense.js
- public/apps/configuration-react/pages/SystemStatus/components/UploadLicense/index.js
- public/apps/configuration-react/pages/SystemStatus/components/index.js
- public/apps/configuration-react/pages/SystemStatus/index.js
- public/apps/configuration-react/pages/SystemStatus/utils/constants.js
- public/apps/configuration-react/pages/SystemStatus/utils/get_resource.js
- public/apps/configuration-react/pages/SystemStatus/utils/index.js
- public/apps/configuration-react/services/BrowserStorage.js
- public/apps/configuration-react/services/SystemService.js
- public/apps/configuration-react/services/index.js
- public/apps/configuration-react/utils/constants.js
- public/apps/configuration-react/utils/helpers.js
- public/apps/configuration-react/utils/i18n/common.js
- public/apps/configuration-react/utils/i18n/system_status.js
- public/apps/configuration/sections/system/controller.js
This closes https://floragunn.atlassian.net/browse/ITT-2006
> System page

- public/apps/configuration-react/index.js
- public/apps/configuration-react/pages/Auth/Auth.js
- public/apps/configuration-react/pages/CreateInternalUser/containers/CreateInternalUser/CreateInternalUser.js
- public/apps/configuration-react/pages/Home/Home.js
- public/apps/configuration-react/pages/InternalUsers/containers/InternalUsers/InternalUsers.js
- public/apps/configuration-react/pages/Main/Main.js
- public/apps/configuration-react/pages/SystemStatus/SystemStatus.js
- public/apps/configuration-react/pages/SystemStatus/components/UploadLicense/UploadLicense.js
- public/apps/configuration-react/utils/i18n/common.js
- public/apps/configuration-react/utils/i18n/home.js
This closes https://floragunn.atlassian.net/browse/ITT-2134
> Add purge cache

- public/apps/configuration-react/components/Breadcrumbs/Breadcrumbs.js
- public/apps/configuration-react/index.js
- public/apps/configuration-react/pages/CreateInternalUser/components/UserCredentials/UserCredentials.js
- public/apps/configuration-react/pages/CreateInternalUser/containers/CreateInternalUser/CreateInternalUser.js
- public/apps/configuration-react/pages/CreateInternalUser/containers/CreateInternalUser/utils/user_to_formik.js
- public/apps/configuration-react/pages/CreateTenant/CreateTenant.js
- public/apps/configuration-react/pages/CreateTenant/index.js
- public/apps/configuration-react/pages/CreateTenant/utils/constants.js
- public/apps/configuration-react/pages/CreateTenant/utils/formik_to_tenant.js
- public/apps/configuration-react/pages/CreateTenant/utils/index.js
- public/apps/configuration-react/pages/CreateTenant/utils/tenant_to_formik.js
- public/apps/configuration-react/pages/Home/Home.js
- public/apps/configuration-react/pages/InternalUsers/containers/InternalUsers/InternalUsers.js
- public/apps/configuration-react/pages/Main/Main.js
- public/apps/configuration-react/pages/Tenants/Tenants.js
- public/apps/configuration-react/pages/Tenants/index.js
- public/apps/configuration-react/pages/Tenants/utils/index.js
- public/apps/configuration-react/pages/Tenants/utils/resources_to_ui_resources.js
- public/apps/configuration-react/pages/Tenants/utils/ui_resource_to_resource.js
- public/apps/configuration-react/utils/constants.js
- public/apps/configuration-react/utils/i18n/common.js
- public/apps/configuration-react/utils/i18n/home.js
- public/apps/configuration-react/utils/i18n/tenants.js
- public/apps/configuration-react/utils/validation.js
- public/apps/configuration/sections/tenants/controller.js
This closes https://floragunn.atlassian.net/browse/ITT-2013
> Tenants page

- public/apps/configuration-react/components/Breadcrumbs/Breadcrumbs.js
- public/apps/configuration-react/index.js
- public/apps/configuration-react/pages/CreateRole/CreateRole.js
- public/apps/configuration-react/pages/CreateRoleMapping/CreateRoleMapping.js
- public/apps/configuration-react/pages/CreateRoleMapping/index.js
- public/apps/configuration-react/pages/CreateRoleMapping/utils/constants.js
- public/apps/configuration-react/pages/CreateRoleMapping/utils/formik_to_role_mapping.js
- public/apps/configuration-react/pages/CreateRoleMapping/utils/index.js
- public/apps/configuration-react/pages/CreateRoleMapping/utils/role_mapping_to_formik.js
- public/apps/configuration-react/pages/Home/Home.js
- public/apps/configuration-react/pages/Main/Main.js
- public/apps/configuration-react/pages/RoleMappings/RoleMappings.js
- public/apps/configuration-react/pages/RoleMappings/index.js
- public/apps/configuration-react/pages/RoleMappings/utils/index.js
- public/apps/configuration-react/pages/RoleMappings/utils/resources_to_ui_resources.js
- public/apps/configuration-react/pages/RoleMappings/utils/ui_resource_to_resource.js
- public/apps/configuration-react/pages/index.js
- public/apps/configuration-react/utils/constants.js
- public/apps/configuration-react/utils/i18n/role_mappings.js
This closes https://floragunn.atlassian.net/browse/ITT-2011
> Add RoleMappings and CreateRoleMapping page

- public/apps/configuration-react/pages/CreateInternalUser/CreateInternalUser.js
- public/apps/configuration-react/pages/CreateInternalUser/components/BackendRoles/BackendRoles.js
- public/apps/configuration-react/pages/CreateInternalUser/utils/index.js
- public/apps/configuration-react/pages/CreateInternalUser/utils/user_to_formik.js
- public/apps/configuration-react/pages/CreateRoleMapping/CreateRoleMapping.js
- public/apps/configuration-react/pages/CreateRoleMapping/utils/constants.js
- public/apps/configuration-react/pages/CreateRoleMapping/utils/index.js
- public/apps/configuration-react/pages/CreateRoleMapping/utils/role_mapping_to_formik.js
- public/apps/configuration-react/pages/Main/Main.js
- public/apps/configuration-react/utils/helpers.js
- public/apps/configuration-react/utils/i18n/roles.js
This closes https://floragunn.atlassian.net/browse/ITT-2154
> Load backend roles and users

- public/apps/configuration-react/components/FormControls/FormikRadio/FormikRadio.js
- public/apps/configuration-react/pages/CreateRole/components/IndexPermissions/FieldLevelSecurity.js
- public/apps/configuration-react/pages/CreateRole/utils/constants.js
- public/apps/configuration-react/pages/CreateRole/utils/role_to_formik.js
- public/apps/configuration-react/pages/Roles/utils/ui_resource_to_resource.js
This closes https://floragunn.atlassian.net/browse/ITT-2168
> Fix Create Role page radio buttons

- index.js
- lib/xff/xff.js
This PR makes it possible to forcefully add X-Forwarded-For headers to calls from KI to ES
> ITT-2150 add proxy headers

- public/apps/configuration-react/pages/CreateRole/CreateRole.js
- public/apps/configuration-react/pages/CreateRoleMapping/CreateRoleMapping.js
- public/apps/configuration-react/pages/CreateRoleMapping/utils/role_mapping_to_formik.js
- public/apps/configuration-react/utils/i18n/role_mappings.js
This closes https://floragunn.atlassian.net/browse/ITT-2167
Screenshot
> Do not save undefined role mapping

- lib/configuration/validation/actiongroups.js
- public/apps/configuration-react/pages/ActionGroups/ActionGroups.js
- public/apps/configuration-react/pages/ActionGroups/utils/resources_to_ui_resources.js
- public/apps/configuration-react/pages/ActionGroups/utils/ui_resource_to_resource.js
- public/apps/configuration-react/pages/CreateActionGroup/CreateActionGroup.js
- public/apps/configuration-react/pages/CreateActionGroup/utils/action_group_to_formik.js
- public/apps/configuration-react/pages/CreateActionGroup/utils/constants.js
- public/apps/configuration-react/pages/CreateActionGroup/utils/formik_to_action_group.js
- public/apps/configuration-react/utils/i18n/common.js
- public/apps/configuration/backend_api/actiongroups.js
This closes https://floragunn.atlassian.net/browse/ITT-2157
> Add type to CreateActionGroup page

- lib/auth/routes.js
- lib/auth/routes_authinfo.js
- lib/backend/searchguard.js
- lib/backend/searchguard_plugin.js
- lib/configuration/backend/searchguard_configuration_backend.js
- lib/configuration/backend/searchguard_configuration_plugin.js
- lib/configuration/routes/routes.js
- lib/configuration/validation/actiongroups.js
- lib/configuration/validation/internalusers.js
- lib/configuration/validation/roles.js
- lib/configuration/validation/rolesmapping.js
- lib/configuration/validation/tenants.js
- lib/elasticsearch/setup_index_template.js
- lib/hapi/auth.js
- lib/jwt/headers.js
- lib/multitenancy/headers.js
- lib/multitenancy/kibana_migrator.js
- lib/multitenancy/migrate_tenants.js
- lib/multitenancy/routes.js
- lib/session/sessionPlugin.js
- lib/system/routes.js
- package.json
- yarn.lock
This closes https://floragunn.atlassian.net/browse/ITT-2188
> Remove es unused modules and require KibanaMigrator inside a separate module

- public/apps/configuration-react/less/main.less
- public/apps/configuration-react/pages/Auth/Auth.js
- public/apps/configuration-react/pages/SystemStatus/SystemStatus.js
- public/apps/configuration-react/pages/SystemStatus/utils/get_resource.js
This closes https://floragunn.atlassian.net/browse/ITT-2196
monitors
> Auth and SystemStatus visual improvements

- public/apps/configuration-react/pages/Main/Main.js
- public/apps/configuration-react/pages/RoleMappings/RoleMappings.js
- public/apps/configuration-react/pages/RoleMappings/utils/get_corresponding_roles.js
- public/apps/configuration-react/pages/RoleMappings/utils/get_corresponding_roles.test.js
- public/apps/configuration-react/pages/RoleMappings/utils/index.js
- public/apps/configuration-react/pages/RoleMappings/utils/resources_to_ui_resources.js
- public/apps/configuration-react/pages/RoleMappings/utils/resources_to_ui_resources.test.js
- public/apps/configuration-react/pages/RoleMappings/utils/ui_resource_to_resource.js
- public/apps/configuration-react/pages/RoleMappings/utils/ui_resource_to_resource.test.js
- public/apps/configuration-react/utils/errors/HttpError.js
- public/apps/configuration-react/utils/errors/index.js
- public/apps/configuration-react/utils/i18n/role_mappings.js
This closes https://floragunn.atlassian.net/browse/ITT-2193
> Show alert in RoleMappings table if there is no corresponding role

- public/apps/configuration-react/pages/CreateRole/CreateRole.js
- public/apps/configuration-react/pages/CreateRole/components/IndexPermissions/IndexPatterns.js
- public/apps/configuration-react/pages/CreateRole/components/IndexPermissions/IndexPermissions.js
- public/apps/configuration-react/pages/CreateRole/utils/formik_to_role.js
- public/apps/configuration-react/pages/CreateRole/utils/formik_to_role.test.js
- public/apps/configuration-react/pages/CreateRole/utils/role_to_formik.js
- public/apps/configuration-react/pages/CreateRole/utils/role_to_formik.test.js
- public/apps/configuration-react/services/SystemService.js
- public/apps/configuration-react/utils/constants.js
- public/apps/configuration-react/utils/i18n/roles.js
- public/apps/configuration-react/utils/validation.js
- public/apps/configuration-react/utils/validation.test.js
This closes https://floragunn.atlassian.net/browse/ITT-2194
> Add backend DLS query check

- public/apps/configuration-react/pages/CreateRole/components/IndexPermissions/IndexPatterns.js
- public/apps/configuration-react/utils/i18n/roles.js
- public/apps/configuration-react/utils/validation.js
- public/apps/configuration-react/utils/validation.test.js
This closes https://floragunn.atlassian.net/browse/ITT-2199
> Fix typo DSL must be DLS

- public/apps/configuration/backend_api/tenants.js
This PR fixes a bug that prevented new tenants from being saved.
> ITT-2237 - Fixed bug when saving a new tenant

- public/apps/configuration-react/pages/CreateActionGroup/CreateActionGroup.js
- public/apps/configuration-react/pages/CreateInternalUser/components/BackendRoles/BackendRoles.js
- public/apps/configuration-react/pages/CreateRole/components/ClusterPermissions/ClusterPermissions.js
- public/apps/configuration-react/pages/CreateRole/components/IndexPermissions/FieldLevelSecurity.js
- public/apps/configuration-react/pages/CreateRole/components/IndexPermissions/IndexPatterns.js
- public/apps/configuration-react/pages/CreateRole/components/TenantPermissions/TenantPatterns.js
- public/apps/configuration-react/pages/CreateRoleMapping/CreateRoleMapping.js
- public/apps/configuration-react/pages/Main/Main.js
- public/apps/configuration-react/utils/validation.js
- public/apps/configuration-react/utils/validation.test.js
This closes https://floragunn.atlassian.net/browse/ITT-2217
> (Note: This happens for all resources when I do not provide at least a name)
I found this happening only in Create Role Mapping.
1. Go to Role Mappings
2. Click Create Role Mapping button
3. Click Save button
4. You should see validation error **Required** below the Role ComboBox
6. Select a role. The error should disappear
> Validate Role ComboBox in CreateRoleMapping page.

- public/apps/configuration-react/pages/CreateRole/CreateRole.js
- public/apps/configuration-react/pages/CreateRole/components/IndexPermissions/IndexPatterns.js
- public/apps/configuration-react/pages/CreateRole/components/IndexPermissions/IndexPermissions.js
- public/apps/configuration-react/pages/CreateRole/components/TenantPermissions/TenantPatterns.js
- public/apps/configuration-react/pages/CreateRole/components/TenantPermissions/TenantPermissions.js
- public/apps/configuration-react/pages/Main/Main.js
This closes https://floragunn.atlassian.net/browse/ITT-2229
1. Go to Crate Role page
2. Go to Index Permissions tab
3. Add a pattern
4. Try to delete it
5. You should see the confirmation modal
6. The pattern is deleted if you press the Confirm button
7. Go to Tenant Permissions tab
8. Do steps 3-6
> Create Role. Confirm index and tenant patterns deletion.

- public/apps/configuration-react/pages/CreateActionGroup/CreateActionGroup.js
- public/apps/configuration-react/pages/CreateInternalUser/CreateInternalUser.js
- public/apps/configuration-react/pages/CreateRole/CreateRole.js
- public/apps/configuration-react/pages/CreateRoleMapping/CreateRoleMapping.js
- public/apps/configuration-react/pages/CreateTenant/CreateTenant.js
- public/apps/configuration-react/pages/Main/Main.js
- public/apps/configuration-react/pages/SystemStatus/components/UploadLicense/UploadLicense.js
This closes https://floragunn.atlassian.net/browse/ITT-2212
1. Go to any Create <Item> page
2. Click inspect button
3. See a flyout appear
4. Navigate to any other page
4. See the flyout disappear
> Close flyout on component unmount.

- public/apps/configuration-react/components/Breadcrumbs/Breadcrumbs.js
This closes https://floragunn.atlassian.net/browse/ITT-2219
1. Go to any of the following pages Update User, Update Role Mapping, Update Role, Update Action Group and Update Tenant
2. Click on the **Update \<Name\>** breadcrumb
3. You should stay on the same page
> Disable Update <Items> breadcrumb link.

- public/apps/configuration-react/pages/CreateTenant/CreateTenant.js
This closes https://floragunn.atlassian.net/browse/ITT-2222
1. Go to Create Tenant page
2. Click Save button
3. See no validation error below Description field
> Make tenant description field optional.

- public/apps/configuration-react/pages/CreateRole/components/Overview/Overview.js
This closes https://floragunn.atlassian.net/browse/ITT-2226
1. Go to Create Role page
2. Find the Backend Roles text label
> Use correct text label for backend roles.

- public/apps/configuration-react/components/DynamicValuesForm/DynamicValuesForm.js
- public/apps/configuration-react/components/Page/TitleSecondary/TitleSecondary.js
- public/apps/configuration-react/components/Page/TitleSecondary/index.js
- public/apps/configuration-react/components/index.js
- public/apps/configuration-react/pages/CreateActionGroup/CreateActionGroup.js
- public/apps/configuration-react/pages/CreateActionGroup/utils/action_group_to_formik.js
- public/apps/configuration-react/pages/CreateActionGroup/utils/action_group_to_formik.test.js
- public/apps/configuration-react/pages/CreateInternalUser/components/UserAttributes/UserAttributes.js
- public/apps/configuration-react/pages/CreateRole/components/ClusterPermissions/ClusterPermissions.js
- public/apps/configuration-react/pages/CreateRole/components/IndexPermissions/FieldLevelSecurity.js
- public/apps/configuration-react/pages/CreateRole/components/IndexPermissions/IndexPatterns.js
- public/apps/configuration-react/pages/CreateRole/components/Overview/Overview.js
- public/apps/configuration-react/pages/CreateRole/components/TenantPermissions/TenantPatterns.js
- public/apps/configuration-react/pages/CreateRole/utils/constants.js
- public/apps/configuration-react/pages/CreateRole/utils/role_to_formik.js
- public/apps/configuration-react/pages/CreateRole/utils/role_to_formik.test.js
This closes https://floragunn.atlassian.net/browse/ITT-2221 and closes https://floragunn.atlassian.net/browse/ITT-2228
> Switch on isAdvanced when there is at least one Single permission

- public/apps/configuration-react/pages/CreateActionGroup/utils/action_group_to_formik.js
- public/apps/configuration-react/pages/CreateInternalUser/CreateInternalUser.js
- public/apps/configuration-react/pages/CreateRole/CreateRole.js
- public/apps/configuration-react/pages/CreateRole/utils/constants.js
- public/apps/configuration-react/pages/CreateRole/utils/formik_to_role.js
- public/apps/configuration-react/pages/CreateRole/utils/formik_to_role.test.js
- public/apps/configuration-react/pages/CreateRole/utils/role_to_formik.js
- public/apps/configuration-react/pages/CreateRole/utils/role_to_formik.test.js
- public/apps/configuration-react/pages/CreateRoleMapping/CreateRoleMapping.js
- public/apps/configuration-react/pages/CreateRoleMapping/utils/formik_to_role_mapping.js
- public/apps/configuration-react/pages/CreateRoleMapping/utils/formik_to_role_mapping.test.js
- public/apps/configuration-react/pages/InternalUsers/InternalUsers.js
- public/apps/configuration-react/pages/RoleMappings/RoleMappings.js
- public/apps/configuration-react/pages/RoleMappings/utils/ui_resource_to_resource.js
- public/apps/configuration-react/pages/RoleMappings/utils/ui_resource_to_resource.test.js
- public/apps/configuration-react/pages/Roles/Roles.js
- public/apps/configuration-react/pages/Roles/utils/resources_to_ui_resources.js
- public/apps/configuration-react/pages/Roles/utils/resources_to_ui_resources.test.js
- public/apps/configuration-react/pages/Roles/utils/ui_resource_to_resource.js
- public/apps/configuration-react/pages/Roles/utils/ui_resource_to_resource.test.js
- public/apps/configuration-react/pages/Tenants/Tenants.js
- public/apps/configuration-react/utils/helpers/helpers.test.js
- public/apps/configuration-react/utils/helpers/index.js
- public/apps/configuration/backend_api/roles.js
- public/apps/configuration/backend_api/rolesmapping.js
- public/apps/configuration/backend_api/tenants.js
This closes https://floragunn.atlassian.net/browse/ITT-2259
1. Go to Roles page
2. Select some role to edit
3. Go to Cluster Permissions tab
4. Add some action groups and single permissions
5. Go to Index Permissions tab
6. Select/add a Index Pattern
7.  Add some action groups and single permissions
8. Save the role
9. Clone it
10. Select the cloned role for edit
11. See all the stuff added before present in the cloned role
> Fix data structure

- public/apps/configuration-react/components/Table/TableCloneAction/TableCloneAction.js
- public/apps/configuration-react/components/Table/TableDeleteAction/TableDeleteAction.js
- public/apps/configuration-react/components/Table/TableNameCell/TableNameCell.js
- public/apps/configuration-react/components/Table/TableSwitchSystemItems/TableSwitchSystemItems.js
- public/apps/configuration-react/components/Table/TableSwitchSystemItems/index.js
- public/apps/configuration-react/components/Table/TableTextCell/TableTextCell.js
- public/apps/configuration-react/components/index.js
- public/apps/configuration-react/pages/ActionGroups/ActionGroups.js
- public/apps/configuration-react/pages/InternalUsers/InternalUsers.js
- public/apps/configuration-react/pages/RoleMappings/RoleMappings.js
- public/apps/configuration-react/pages/Roles/Roles.js
- public/apps/configuration-react/pages/Tenants/Tenants.js
This closes https://floragunn.atlassian.net/browse/ITT-2265
1. Go to any page with tabel
2. Inspect some table columns HTML elements
3. All columns must contain `data-test-subj` attribute value of the format 
```
sgTableCol-<ColName|ActionType>-<item>
```
4. Inspect System Items switch. The related HTML element must have the following attribute
```
data-test-subj="sgTableSwitchSystemItems"
```
> Make data test subj value consistent

- public/apps/configuration-react/pages/CreateRole/components/IndexPermissions/DocumentLevelSecurity.js
- public/apps/configuration-react/pages/CreateRole/components/IndexPermissions/FieldLevelSecurity.js
- public/apps/configuration-react/pages/CreateRole/components/IndexPermissions/IndexPatterns.js
This closes https://floragunn.atlassian.net/browse/ITT-2230
1. Go to Create Role page
2. Go to Index Permissions tab
3. Create or edit an Index Pattern
4. Put the following query in Document Level Security editor
```
{ "bool": { "must_not": { "match": { "department": "Management" }}}}
```
5. Click Check button
6. See the query formatted
7. Substitute the query in the editor by `{"a":1}`
8. Click Check button
9. See the new query formatted and validation error: **DLS query syntax is invalid**
> Manually validate and format DLS query

- public/apps/configuration-react/pages/SystemStatus/SystemStatus.js
- public/apps/configuration-react/pages/SystemStatus/components/SystemStatusContent.js
- public/apps/configuration-react/pages/SystemStatus/components/index.js
This closes https://floragunn.atlassian.net/browse/ITT-2268
See the issue description to check this PR.
> System Status. Fix license info. Data should be fetched again if component updated.

- public/apps/configuration-react/components/Table/TableDeleteAction/TableDeleteAction.js
- public/apps/configuration-react/pages/ActionGroups/ActionGroups.js
- public/apps/configuration-react/pages/InternalUsers/InternalUsers.js
- public/apps/configuration-react/pages/RoleMappings/RoleMappings.js
- public/apps/configuration-react/pages/Roles/Roles.js
- public/apps/configuration-react/pages/Tenants/Tenants.js
This closes https://floragunn.atlassian.net/browse/ITT-2267
To check this pr
1. Go to any page with a table
2. See table action buttons aligned properly in each row
3. Reserved items have the delete action disabled
> Align table action buttons. Reserved items have delete action button disabled

- public/apps/configuration-react/pages/SystemStatus/SystemStatus.js
This closes https://floragunn.atlassian.net/browse/ITT-2268
> Fix license info refresh

- lib/auth/types/AuthType.js
- lib/auth/types/basicauth/BasicAuth.js
- lib/auth/types/jwt/Jwt.js
- lib/auth/types/openid/OpenId.js
- lib/auth/types/proxycache/ProxyCache.js
- lib/auth/types/saml/Saml.js
- lib/backend/searchguard.js
- lib/session/sessionPlugin.js
This PR introduces support for the user impersonation feature for all auth types except Kerberos and Proxy.
> ITT-2234 - Handle user impersonation settings

- public/apps/configuration-react/less/main.less
- public/apps/configuration-react/pages/ActionGroups/ActionGroups.js
- public/apps/configuration-react/pages/InternalUsers/InternalUsers.js
- public/apps/configuration-react/pages/RoleMappings/RoleMappings.js
- public/apps/configuration-react/pages/Roles/Roles.js
- public/apps/configuration-react/pages/Tenants/Tenants.js
This closes https://floragunn.atlassian.net/browse/ITT-2280
1. Go to all pages with tables
2. Make sure System Items switch is off
3. Try to use pagination. It should work fine.
> Make table pagination work if System Items switch is off.

- public/directives/licensewarning.js
> Fix angular directive license error

- lib/auth/types/AuthType.js
This PR fixes an error where a previous invalid session error would not be cleared correctly.
> ITT-2389 - Clear session error

- index.js
- lib/backend/searchguard.js
Show a warning in the Kibana logs if do not fail on forbidden is false
> ITT-1814 - Warn if DNFOF is false

- public/apps/signals/pages/DefineDestination/DefineDestination.js
- public/apps/signals/pages/DefineWatch/components/WatchIndex/WatchIndex.js
- public/apps/signals/pages/Destinations/Destinations.js
- public/apps/signals/pages/Watches/Watches.js
This closes https://floragunn.atlassian.net/browse/LRT-504
> Fix uncrontrolled input

- public/apps/components/FormControls/FormikFieldNumber/FormikFieldNumber.js
This closes https://floragunn.atlassian.net/browse/LRT-490
> Fix a typo in FormikFieldNumber.

- public/apps/components/FormControls/FormikFieldNumber/FormikFieldNumber.js
- public/apps/components/FormControls/FormikFieldPassword/FormikFieldPassword.js
- public/apps/components/FormControls/FormikFieldText/FormikFieldText.js
- public/apps/components/FormControls/FormikSelect/FormikSelect.js
- public/apps/components/FormControls/FormikSwitch/FormikSwitch.js
- public/apps/components/FormControls/FormikTextArea/FormikTextArea.js
- public/apps/signals/pages/DefineWatch/components/GeneralPanel/GeneralPanel.js
This closes https://floragunn.atlassian.net/browse/LRT-496
> Make formik switch helper set checked value. Add id for formik components

- examples/watches/avg_ticket_price/avg_ticket_price.json
- examples/watches/avg_ticket_price/avg_ticket_price_graph.json
- examples/watches/bad_weather/bad_weather.json
- examples/watches/change_in_memory/change_in_memory.json
- examples/watches/max_memory/max_memory.json
- examples/watches/max_memory/max_memory_graph.json
- examples/watches/memory_usage/memory_usage.json
- examples/watches/min_product_price/min_product_price.json
- examples/watches/min_product_price/min_product_price_graph.json
This closes https://floragunn.atlassian.net/browse/LRT-495
> Fix a typo in watch examples.

- public/apps/signals/pages/DefineWatch/DefineWatch.js
- public/apps/signals/pages/DefineWatch/components/ActionPanel/ActionPanel.js
- public/apps/signals/pages/DefineWatch/components/Actions/EmailAction/EmailAction.js
- public/apps/signals/pages/DefineWatch/components/DefinitionPanel/DefinitionPanel.js
- public/apps/signals/pages/DefineWatch/components/GraphWatch/GraphWatch.js
- public/apps/signals/pages/DefineWatch/components/WatchIndex/WatchIndex.js
- public/apps/signals/pages/Main/Main.js
This closes https://floragunn.atlassian.net/browse/LRT-491
> Trigger confirm modal for action removal and for some comboboxes items removal

- public/apps/signals/pages/DefineWatch/components/WatchSchedule/Frequencies/Daily/Daily.js
- public/apps/signals/pages/DefineWatch/components/WatchSchedule/Frequencies/Weekly/Weekly.js
- public/apps/signals/pages/DefineWatch/utils/buildFormikSchedule.js
- public/apps/signals/pages/DefineWatch/utils/buildFormikSchedule.test.js
- public/apps/signals/pages/DefineWatch/utils/formikToWatch.js
- public/apps/signals/pages/DefineWatch/utils/watchToFormik.js
This closes https://floragunn.atlassian.net/browse/LRT-509
> Signals fix daily and weekly schedule

- lib/signals/routes/watch/execute.js
- lib/signals/routes/watch/execute.test.js
- public/apps/signals/services/WatchService.js
This https://floragunn.atlassian.net/browse/LRT-511
> Json watch. Execute checks only.

- public/apps/signals/pages/DefineDestination/utils/formikToDestination.js
- public/apps/signals/utils/helpers.js
- public/apps/utils/helpers/filterEmptyKeys.js
- public/apps/utils/helpers/filterEmptyKeys.test.js
- public/apps/utils/helpers/index.js
This closes https://floragunn.atlassian.net/browse/LRT-512
> Signals accounts (destinations). Dont submit empty fields.

- public/apps/signals/pages/DefineDestination/utils/defaults.js
- public/apps/signals/pages/Destinations/utils/constants.js
This closes https://floragunn.atlassian.net/browse/LRT-513
> Signals account type is in lowercase now due to the change in ES plugin.

- build.sh
- yarn.lock
Closes https://floragunn.atlassian.net/browse/ITT-2381 and closes https://floragunn.atlassian.net/browse/ITT-2397
> WIP. Fix yarn pkgs vulnerabilities. Add yarn audit to build script.

- build.sh
- lib/auth/routes_authinfo.js
Closes https://floragunn.atlassian.net/browse/ITT-2387
> Avoid internal IP disclosure pattern

- lib/system/routes.js
- package.json
- tests/setup_tests.js
- yarn.lock
Closes https://floragunn.atlassian.net/browse/ITT-2388
Please note that if you want to change the Kibana Content-Security-Policy rules you should add the rules in file kibana/config/kibana.yml, for example
```
csp.rules: ["script-src 'unsafe-eval' 'nonce-{nonce}'", "worker-src blob:", "child-src blob:"]
```
https://github.com/elastic/kibana/blob/master/docs/setup/settings.asciidoc
https://github.com/elastic/kibana/blob/master/src/legacy/server/config/schema.js#L57
> Fix headers security
