floragunncom/search-guard-kibana-plugin

public/apps/configuration/backend_api/client.js
public/apps/configuration/configuration.html

This fixes issues where Kibana is loaded using a basePath:
* Logo image on the home screen
* The AJAX calls get the basePath added to each request
This PR only concerns the frontend.

IT-1116 Frontend: Config GUI does not work when base path is enabled

---

lib/configuration/backend/searchguard_configuration_plugin.js

6.1.1
6.1.1
6.1.1-20.1
6.1.1
macOS High Sierra
Chromium 54.0.2816.0 (64-bit)
----
Hi, 
in my kibana setup, I use searchguard combined with Own Home. Own Home is used as a proxy between searchguard and elasticsearch. 
After I updated my stack on 6.1.1 I get a timeout error after each login. I can fix this behaviour when I disable the Own Home plugin.
However, I would like to keep on using the Own Home plugin.
On login, searchguard sends a request `_searchguard/api/permissioninfo` to the ownhome proxy which should forward the request to elasticsearch. 
But the ownhome proxy throws a timeout error and elasticsearch never gets the request.  
When adding a `/` at the beginning of the request it works resulting in searchguard getting a response.
There are different kinds of requests in …

Fixed timeout error on login

---

public/apps/configuration/sections/rolesmapping/views/edit.html

This PR disables already mapped Search Guard Roles when adding a new Role Mapping.

ITT-888 - Disable already mapped Search Guard roles in new role mappings

---

public/apps/login/login.html
public/apps/login/login.less
public/directives/licensewarning.js

This change prevents submitting the login form when one or both fields is/are empty.
I also changed the digest for the license hint - it wouldn't show on page load and instead show up in the next digestion cycle.

ITT-1098 - Prevent submitting an empty login form

---

lib/hapi/auth.js
public/chrome/configuration/enable_configuration.js

Addresses #53 
This PR introduces an error interceptor that checks for 401 errors on any $http calls.
To avoid intercepting all errors, this interceptor checks for a "redirect" property on the response payload. If the property is present, we redirect to the login page, otherwise we just pass the error through. Hopefully, this avoids any unintended side effects, current or future.

ITT-1167 - Handle session timeouts

---

public/apps/configuration/directives/directives.js
public/apps/configuration/directives/form_focusfield/form_focusaddedfield.js
public/apps/configuration/directives/form_focusfield/form_focusfield.js
public/apps/configuration/sections/actiongroups/views/edit.html
public/apps/configuration/sections/internalusers/views/edit.html
public/apps/configuration/sections/roles/views/edit.html
public/apps/configuration/sections/rolesmapping/views/edit.html

This PR adds two directives that will help setting focus on dynamically added or dynamically shown input fields. Probably not very important, but it may improve the UX a bit by reducing the number of clicks and tabs necessary.
form_focusaddedfield.js - This adds a native MutationObserver that checks for changes to the DOM. It is somewhat simplified to work on the use cases we currently have, but could be easily extended if needed. It works by checking for added nodes and then searches those nodes for an input field of type text. 
form_focusfield.js - This is a typical Angular directive that takes a parameter that, when it switches from false or undefined to true, sets the focus on an element.

ITT-1140 - Add focus to dynamically created form fields

---

public/apps/configuration/sections/roles/controller.js

Fixes the UI state after deleting the last documentType for an index defined in a role.
When the index itself is deleted, we chose the next index available.
If we deleted the last index from the list, we select the index that came prior to the deleted index in the list.
I kept the current behaviour for when the last index is deleted.

ITT-1276 - After deleting an index from a role, auto-select the next existing

---

public/apps/configuration/sections/roles/views/edit.html

Fixes a possible bug that would save a role after the user clicks cancel in the role edit mode.

ITT-1289 - Don't save the role when clicking "cancel"

---

index.js
lib/auth/routes.js

Adds a configuration option to kibana.yml that can be used to prevent access for certain usernames:
`searchguard.basicauth.forbiddenUserNames: ['username1', 'username2']`
If a forbidden username is detected while trying to login, an AuthenticationError is thrown.

ITT-1088 Restrict basic auth for certain usernames

---

public/apps/login/login.html
public/apps/login/login.less

Fixes #78.
The validation state on the login fields is now fixed by overriding Kibana's default style for invalid elements. Instead, we rely on Angular's validation styles.
I also added an explicit error state for the text fields if we receive an error after submitting the form.
The custom login button styles from the configuration file work now too.
Tested in IE11 on Win7.

ITT-1240 - Login page improvements for IE11

---

public/apps/multitenancy/multitenancy.js
public/chrome/multitenancy/observe_share_links.js
public/chrome/readonly/enable_readonly.js

This PR adds the current tenant to the URLs in the share panel in Dashboard, Visualizations and Discover. If a user opens the link while having another tenant active, the selected tenant is changed to match the target URL, using the already existing support for the sg_tenant parameter.
Coincidentally it also fixes a bug for the read only mode that would occur in some cases when the global tenant is set to read only.
I'm not too happy about invoking this as a part of the enable_readonly.js since it's not really the same topic, but I figured it's better than introducing a new hack app.

ITT-744 - Add tenant to the share urls

---

index.js
public/chrome/readonly/enable_readonly.js

As discussed, this PR introduces a couple of changes to the read only mode
1) Hides the navigation items before all information is resolved and then shows the appropriate links. The original PR did it the other way around.
2) No default role configured
3). If no readonly role is configured, the navigation items from 1) are never hidden

ITT-675 - Hide navigation items before resolving, no configured role by default

---

lib/auth/types/jwt/Jwt.js

This PR removes the case sensitive constraint on the JWT url query parameter

ITT-1533 - Handle casing when extracting the JWT url parameter

---

index.js
lib/auth/types/jwt/Jwt.js

This PR adds the ability to define an external login_endpoint for the JWT AuthType.
If a login_endpoint is configured, the user is redirected to that url if
1) The session has expired, or
2) No valid JWT token found
A "nextUrl" query parameter is appended to the configured login_endpoint.

ITT-1533 - Redirect to JWT login endpoint

---

public/apps/configuration/sections/roles/controller.js
public/apps/configuration/sections/roles/views/index.html
public/chrome/readonly/enable_readonly.js

This PR enables linking to indexnames with a regular expression.
Before, if the indexname started with a "/", Angular's routing would get confused and lead to an empty page.

ITT-1534 - Fix for links that have a regex as one of the parameters

---

lib/auth/types/AuthType.js
lib/hapi/auth.js

Fixes an issue where the plugin would crash while checking for session timeout.
See here https://github.com/floragunncom/search-guard/issues/535 for more information.

ITT-1556 - Better check for request.headers.accept

---

public/apps/configuration/sections/roles/controller.js
public/apps/configuration/sections/roles/index.js
public/apps/configuration/sections/roles/views/index.html

This PR fixes the case where no default index would be selected when editing a role's permissions.
Also, it simplifies they way we handle routes containing a regex, which was the cause for this bug.

ITT-1608 - Roles: Index not preselected anymore on roles tab

---

lib/auth/errors/missing_role_error.js
lib/auth/types/basicauth/BasicAuth.js
lib/auth/types/basicauth/routes.js
lib/auth/types/jwt/Jwt.js
lib/auth/types/openid/OpenId.js
lib/auth/types/saml/Saml.js
lib/session/sessionPlugin.js
public/apps/customerror/errormessage_types.js
public/apps/login/login_controller.js

For every auth type, we know check if the logged in user has a valid role. If not, they will be redirected to the error page with a message saying they should contact the admin.
For basic auth, the error message is shown below the login form instead of a redirect.

ITT-1606 - Block users from logging in when they do not have at least one SG role

---

lib/auth/types/AuthType.js
lib/auth/types/basicauth/BasicAuth.js
lib/auth/types/basicauth/routes.js
lib/session/sessionPlugin.js
public/apps/customerror/errormessage_types.js
public/chrome/configuration/enable_configuration.js

This PR improves handling of the case where an explicitly logged in user's cookie expires. Previously, this would switch the user over to anonymous access. Now you're redirected to the login page instead.
If the user was anonymous, the cookie will be re-created.
This PR also adds an error message if the anonymous access isn't configured properly.

ITT-329 - Kibana Anonymous access v2

---

index.js
lib/auth/types/basicauth/BasicAuth.js

This PR adds a config option for redirecting the user to an absolute URL instead of a relative path when the user is unauthenticated.
In other words, instead of redirecting to /login?nextUrl the user is redirected to https://www.myloadbalancer.com/login?nextUrl
I had some issues while cherry picking this into the feature branch. Please let me know if you run into issues while merging.

ITT-1642 - Redirect to an absolute loadbalancer url instead of a relative path

---

lib/auth/types/AuthType.js

This PR addresses two things:
1. The Boom error we would get when running into an expired session on POST or api requests
2. It also checks the header "content-type" in order to detect an AJAX request better

ITT-1685 - Better check for AJAX requests when session has expired

---

lib/auth/types/saml/routes.js

This PR adds an additional route for IdP-Initiated SSO.
The original route will now redirect to the error page if no RequestId is provided.

ITT-1687 - Support IdP-initiated SSO

---

index.js
lib/auth/types/basicauth/BasicAuth.js

This PR aims to remove the confusion caused when the browser send an authorization header, but we already have a logged in user. Now, if we already have a logged in user, we just ignore the header unless configured not to.
If we don't have a logged in user, we do use the authorization header as usual.

ITT-1775 - Ignore auth header when we have an existing session cookie

---

lib/auth/types/proxycache/parse_login_endpoint.js

Removes the (double) encoding for the login_endpoint.
The url will still be encoded, but only once.

ITT-1769 - Avoid double encoding for next url

---

lib/auth/parseNextUrl.js

This PR handles the situation where we would add two forward slashes when redirecting the user after a successful login. In most cases, two slashes should not create any issues, but at least one customers experienced problems when using a proxy in front of Kibana.

SGCS-193 avoid double slashes in nextUrl

---

index.js
lib/auth/types/AuthType.js

This PR fixes a regression caused by upgrading the hapi-auth-cookie.

ITT-1894 - Use same isSameSite value as before 6.6

---

public/chrome/configuration/enable_configuration.js

This PR fixes the missing navlink icons when having one of SearchGuards app open.
Only needed for 6.6, and the issue has supposedly been fixed in Kibana 6.6.2.

ITT-1896 - Fixed an issue where the navlink icons would disappear in non-Kibana apps

---

lib/auth/types/AuthType.js
lib/multitenancy/headers.js

This PR fixes a merge error for the additionalAuthHeaders and also validates the cookie in onPreAuth.
This needs to be merged into 6.5 as well and requires minor changes because of the different Hapi versions.

ITT-1903 - Improved cookie validation

---

package.json

This PR removes the js-yaml package, which wasn't really used anywhere.

ITT-1998 - Removed unused package

---

index.js
public/services/access_control.js

This PR adds a configurable logout URL for auth types that do not specify their own (Basic Auth, JWT)

make logout url configurable

---

lib/auth/parseNextUrl.js
public/apps/configuration/backend_api/client.js
public/apps/configuration/backend_api/tenants.js
public/apps/login/get_next_url.js
public/chrome/multitenancy/enable_multitenancy.js

This PR allows for special characters in tenant names, such as `$something&_test#`.
The tenant name needs to be encoded, otherwise the *&* and *#* will break the URL. I've added the encoding to the share panel. Also, I removed the decoding from when we parse the nextUrl - it did not have the intended effect.
Fixes https://github.com/floragunncom/search-guard/issues/672.
When we backport this we need to remove the changes in tenants.js - the 6.x format handles this differently.

ITT-2048 - Support special characters in tenant names

---

lib/auth/types/AuthType.js
public/chrome/configuration/enable_configuration.js

This PR handles session timeouts on ajax requests that aren't created by Angular's $http service.
Fixes https://github.com/floragunncom/search-guard/issues/695.
The node part needs to be backported to 6.6. I'll check the frontend part.

ITT-2132 - Handle session timeout on ajax requests

---

public/apps/configuration-react/pages/ActionGroups/ActionGroups.js
public/apps/configuration-react/pages/InternalUsers/InternalUsers.js
public/apps/configuration-react/pages/Main/Main.js
public/apps/configuration-react/pages/RoleMappings/RoleMappings.js
public/apps/configuration-react/pages/Roles/Roles.js
public/apps/configuration-react/pages/Tenants/Tenants.js
public/apps/configuration-react/services/AppCacheService.js
public/apps/configuration-react/services/index.js
public/apps/configuration-react/utils/constants.js
public/apps/configuration-react/utils/helpers/helpers.test.js
public/apps/configuration-react/utils/helpers/index.js
public/apps/configuration-react/utils/i18n/common.js
public/apps/configuration-react/utils/i18n/role_mappings.js

This closes https://floragunn.atlassian.net/browse/ITT-2205
To-do:
1. Visit all the following pages: Internal Users, Role Mappings, Roles, Action Groups and Tenants
2. See a switch with label **System Items** next to the table search bar
3. Reserved and static resources shouldn't be visible in the table
4. Trigger the switch and see the hidden resources
ATTENTION! The switch logic is reversed for Action Groups, look the issue for details.
Screenshots

Add a switch to filter static and reserved table resources.

---

public/apps/multitenancy/multitenancy.js

This PR introduces a check for enabled apps before trying to reset the lastSubUrl when switching tenants. Without the check, `chrome.getNavLinkById(appId)` may throw an error.

ITT-2240 - Multitenancy: Check that apps are enabled before trying to access their properties

---

public/chrome/configuration/enable_configuration.js

This closes https://floragunn.atlassian.net/browse/ITT-2248
1. Add a user with no API access
1.1. Add user to sg_internal_users.yml
```
hr_employee:
hash: "$2a$12$VcCDgh2NDk07JGN0rjGbM.Ad41qVR/YFJcgHp0UGns5JDymv..TOG"
backend_roles:
- "kibanauser"
attributes:
attribute1: "value1"
attribute2: "value2"
attribute3: "value3"
```
1.2. Add role mapping to sg_roles_mapping.yml
```
sg_human_resources:
backend_roles:
- "hr"
- "jwt_hr"
users:
- "hr_employee"
```
1.3. Add role to sg_roles.yml
```
sg_human_resources:
cluster_permissions:
- SGS_CLUSTER_COMPOSITE_OPS
index_permissions:
- index_patterns:
- 'humanresources'
allowed_actions:
- SGS_UNLIMITED
tenant_permissions:
- tenant_patterns:
- human_resources
allowed_actions:
- SGS_KIBANA_ALL_WRITE
- tenant_patterns:
- …
```

Register React app for the left navbar if user has API access and hide the app when there is no access.

---

public/apps/configuration-react/pages/CreateRole/components/ClusterPermissions/ClusterPermissions.js
public/apps/configuration-react/pages/CreateRole/components/IndexPermissions/IndexPatterns.js
public/apps/configuration-react/utils/validation.js
public/apps/configuration-react/utils/validation.test.js

This closes https://floragunn.atlassian.net/browse/ITT-2264
**REBASE THIS BEFORE MERGE!**
To check this PR 
1. Go to Create Role
2. Go to Index Permissions tab
3. Trigger Advanced switch
4. Add `indices:data/read*` to Single Permissions ComboBox
5. See the value accepted
6. Go to Cluster Permissions tab
7. Trigger Advanced switch
8. Add `cluster:a` to Single Permissions ComboBox
9. Add `indices:a`
10. See both options accepted

Allow adding custom values to Index Pattern Single Permissions ComboBox

---

public/apps/configuration-react/pages/CreateActionGroup/utils/constants.js

This PR removes the "kibana" action type. Also, Cluster and Index are now capitalised in the dropdown.

ITT-2220 - Remove action group type "kibana" for now

---

index.js

This PR shows a warning when having es configured to use a ssl certificate and to always present the certificate.

ITT-2350 - Warn when alwaysPresentCertificate is true
